name: base

channels:
  - conda-forge
  - pytorch
  - nordicesmhub
  - bioconda
  - defaults

dependencies:
  - numpy 
  - xarray 
  - pandas
  - cartopy
  - matplotlib 
  - seaborn 
  - geopy 
  - basemap
  - netcdf4
  - cis
  - metpy
