name: base

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - xarray 
  - pandas
  - cartopy
  - geopy 
  - netcdf4
  - cis
  - metpy
  - ipyleaflet
  - rasterio
  - requests
  - pillow
  - branca
  - geopandas
  - cdsapi 
  - folium
  - plotly
  - rasterstats
  - python-ternary
  - cmocean
  - k3d
  - vega_datasets
  - pip:
      - dask_labextension
      - geojsoncontour
      - ipydatawidgets
      - sidecar
