name: base

channels:
  - conda-forge
  - pytorch
  - nordicesmhub
  - bioconda
  - defaults

dependencies:
  - numpy 
  - xarray 
  - pandas
  - cartopy
  - matplotlib 
  - seaborn 
  - geopy 
  - basemap
  - netcdf4
  - cis
  - metpy
  - ipyleaflet
  - scipy
  - rasterio
  - tqdm
  - requests
  - pillow
  - branca
  - geopandas
  - ncl
  - cdsapi 
  - folium
  - basemap-data-hires
  - plotly
  - rasterstats
  - astropy
  - python-ternary
  - ipyvolume
  - pip:
      - dask_labextension
      - geojsoncontour
      - ipydatawidgets
      - sidecar
      - k3d
