name: base

channels:
  - conda-forge
  - pytorch
  - nordicesmhub
  - bioconda
  - defaults

dependencies:
  - numpy 
  - xarray 
  - pandas
  - cartopy
  - matplotlib 
  - seaborn 
  - geopy 
  - basemap
  - netcdf4
  - cis
  - metpy
  - ipyleaflet=0.9.2
  - scipy
  - rasterio
  - tqdm
  - requests
  - pillow
  - branca
  - geopandas
  - cv2
  - voila
  - nodejs
  - pythreejs
  - bqplot
  - pip:
      - dask_labextension
      - ipydatawidgets
      - sidecar
